INSERT INTO CATEGORIA(ID, DESCRICAO)
VALUES(NEWID(), 'DESPESAS DE ALIMENTAÇÃO');

INSERT INTO CATEGORIA(ID, DESCRICAO)
VALUES(NEWID(), 'DESPESAS DE CASA');

INSERT INTO CATEGORIA(ID, DESCRICAO)
VALUES(NEWID(), 'DESPESAS DE CARTÃO DE CRÉDITO');

INSERT INTO CATEGORIA(ID, DESCRICAO)
VALUES(NEWID(), 'DESPESAS DE SAÚDE');

INSERT INTO CATEGORIA(ID, DESCRICAO)
VALUES(NEWID(), 'SALÁRIO E RENDA');

INSERT INTO CATEGORIA(ID, DESCRICAO)
VALUES(NEWID(), 'VIAGENS E LAZER');

INSERT INTO CATEGORIA(ID, DESCRICAO)
VALUES(NEWID(), 'OUTROS');

SELECT * FROM CATEGORIA;


